### ISSUE TITLE
Sugestão: Extrator Lattes

### ISSUE THREAD

**Issue by rigille** [jpmenachalco/scriptLattes#13]
Parece que o site do Lattes começou a usar captchas para evitar scrapers, mas eles [disponibilizam os dados](https://memoria.cnpq.br/web/portal-lattes/extracoes-de-dados) por essa via do extator lattes.

**Comment by jpmenachalco** [comment]
Esse site é destinado ao acesso aos currículos Lattes em formato XML, oferecido exclusivamente para instituições de ensino e pesquisa, e limitado a um único IP por instituição. Infelizmente, o scriptLattes não possui suporte para esse tipo de acesso. No entanto, o scriptLattes continua plenamente funcional. Para mais informações e detalhes sobre como o script coleta o dados, por favor veja a seção de vídeo-aulas no Discord.

**Comment by rigille** [comment]
Beleza, vou dar uma olhada obrigado!

**Comment by rigille** [comment]
Parece que o invite do discord expirou, poderia atualizar?
